### ISSUE TITLE
Not Really An Issue

### ISSUE THREAD

**Issue by antmar904** [ricklupton/rmc#1]
Hi
I'd like to use your tool in order for me to read .rm file that were created on a reMarkable 2 tablet but I'm not sure how to use it.  I have your tool downloaded and extracted on my Ubuntu box but not sure where to go from there.  Any help is much appreciated.

**Comment by antmar904** [comment]
Ok.  I installed all dependantcies from the .toml file.  I'm trying to run:

rmc -f /mnt/c/test/file.rm -t /mnt/c/test/test.pdf and i'm getting the following:

**Error: source format /mnt/c/test/file.rm not implemented yet**

**Comment by ricklupton** [comment]
@antmar904 I've added some better instructions to the README and the output of running `rmc --help`. If there's still anything that's not clear please feel free to open another issue.

(`-f` is for the source format, not the source filename)
